/*
 * Master Gradle build script
 *
 * Depends on bndPlugin property set by settings.gradle.
 * and bnd_* values from gradle.properties.
 */
import aQute.bnd.gradle.AbstractBndTask

buildscript {
	dependencies {
		classpath files(bnd_plugin.tokenize(File.pathSeparatorChar))
	}
}

apply plugin: 'biz.aQute.bnd.workspace'

abstract class Build extends AbstractBndTask {

	@Input
	abstract Property<String> getProjectPath()

	@TaskAction
	void execute() {
		if (!getBndWorkspace().isPresent()) {
			throw new GradleException("workspace does not have a Bnd Workspace")
		}
		println "### Project ${projectName} ${projectPath.get()} ${bndWorkspace.get()}"
	}
}

tasks.register('build', Build) {
	getProjectPath().set(project.path)
}
